---
  - name: Update remote system
    apt:
      update_cache: yes

  - name: Install mysqldb python library
    apt:
      name:
        - python3-mysqldb
      state: present

  - name: Install mysql-server
    apt:
      name:
        - mysql-server
      state: present

  - name: Reload mysql
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Setup user
    mysql_user:
      name: wordpress
      password: "wordpress"
      login_user: wordpress
      login_password: "wordpress"
      check_implicit_admin: yes
      host: '%'
      priv: "*.*:ALL,GRANT"
