---
  - src: git@github.com:eksenof/java-role.git
    scm: git
    version: "1.0.1"
    name: java-role

  - src: git@github.com:eksenof/elastic-role.git
    scm: git
    version: "1.0.1"
    name: elastic-role

  - src: git@github.com:eksenof/kibana-role.git
    scm: git
    version: "1.0.1"
    name: kibana-role
