---
- name: Install Java
  hosts: all
  roles:
    - java-role
- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elastic-role
- name: Install Kibana
  hosts: kibana
  roles:
    - kibana-role
