---
# grafana installation
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Download grafana package
    become: true
    get_url:
      url: https://dl.grafana.com/oss/release/grafana_9.1.5_amd64.deb
      dest: /tmp/grafana_9.1.5_amd64.deb 
      use_proxy: yes
    environment:
      https_proxy: 'http://192.168.1.9:3128'

  - name: Update packages
    become: true
    shell: apt --fix-broken -y install

  - name: Install requirements
    become: true
    apt:
      name: 
        - libfontconfig1
        - fontconfig-config

  - name: Install grafana
    become: true
    shell: dpkg -i /tmp/grafana_9.1.5_amd64.deb

  - name: Enable and start grafana service
    service:
      name: grafana-server
      enabled: yes
      state: started

# grafana configuration    
  - name: Create /etc/grafana/provisioning/datasources/
    become: true
    file:
      state: directory
      path: /etc/grafana/provisioning/datasources/
      recurse: true
      owner: "grafana"
      group: "grafana"
      mode: 0755

  - name: Copy the server binary to /etc/grafana/provisioning/datasources/
    become: true
    copy:
      src: "grafana-prometheus-datasource.yml"
      dest: "/etc/grafana/provisioning/datasources/grafana-prometheus-datasource.yml"
      mode: 0664
      owner: "grafana"
      group: "grafana"

  - name: Create /var/lib/grafana/dashboards/
    become: true
    file:
      state: directory
      path: /var/lib/grafana/dashboards/
      recurse: true
      owner: "grafana"
      group: "grafana"
      mode: 0777

  - name: Wait for service up
    uri:
      url: "http://127.0.0.1:3000"
      status_code: 200
    register: __result
    until: __result.status == 200
    retries: 120
    delay: 1

# add dashboards
  - include_tasks: dashboards.yml
