---
  - name: add hosts in local net in hosts file
    become: true
    lineinfile:
      path: /etc/hosts
      line: 
        - 192.168.1.9  nle.eksen.space
        - 192.168.1.10 db01.eksen.space
        - 192.168.1.11 db02.eksen.space
        - 192.168.1.12 app.eksen.space
        - 192.168.1.13 gitlab.eksen.space
        - 192.168.1.14 runner.eksen.space 
        - 192.168.1.15 monitoring.eksen.space

  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Installing nginx
    apt:
      name: nginx
      state: latest

  - name: Disabling default site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Installing nginx configuration
    template:
      src: wordpress.conf
      dest: /etc/nginx/sites-available/wordpress.conf

  - name: Activating site configuration
    file:
      src: '/etc/nginx/sites-available/wordpress.conf'
      dest: '/etc/nginx/sites-enabled/wordpress.conf'
      state: 'link'

  - name: Reloading nginx
    service:
      name: nginx
      state: restarted
      enabled: true

  - name: Installing PHP
    apt: 
      name:
        - php
        - php-fpm
        - php-pear
        - php-mysql
        - php-cgi
        - php-memcache
        - php-memcached
        - php-gd
        - php-curl
        - php-xmlrpc
      state: latest

#  - name: Downloading WordPress
#    get_url:
#      url: https://ru.wordpress.org/wordpress-6.0-ru_RU.tar.gz
#      dest: /tmp/wordpress.tar.gz

  - name: copy wordpress from local pc, because too many requests error from server
    copy:
      src: wordpress.tar.gz
      dest: /tmp/wordpress.tar.gz
    
  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www
      remote_src: yes

  - name: Seting ownership
    file:
      path: /var/www/wordpress
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

#  - name: Coping sample config file
#    command:
#      cmd:  mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php 
#      creates: /var/www/wordpress/wp-config.php

  - name: Installing wp configuration
    template:
      src: wp-config.php
      dest: /var/www/wordpress/wp-config.php
      
 
