---
  - name: Update remote system
    apt:
      update_cache: yes

  - name: Install nginx
    apt:
      name: nginx
      state: latest

  - name: Disable default site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Install nginx configuration
    template:
      src: wordpress.conf
      dest: /etc/nginx/sites-available/wordpress.conf

  - name: Activate site configuration
    file:
      src: '/etc/nginx/sites-available/wordpress.conf'
      dest: '/etc/nginx/sites-enabled/wordpress.conf'
      state: 'link'

  - name: Reload nginx
    service:
      name: nginx
      state: restarted
      enabled: true

  - name: Install PHP
    apt: 
      name:
        - php
        - php-fpm
        - php-pear
        - php-mysql
        - php-cgi
        - php-memcache
        - php-memcached
        - php-gd
        - php-curl
        - php-xmlrpc
      state: latest

  - name: Downloading WordPress
    get_url:
      url: https://ru.wordpress.org/wordpress-6.0-ru_RU.tar.gz
      dest: /tmp/wordpress.tar.gz
    environment:
      https_proxy: 'http://192.168.1.9:3128'

#  - name: Copy wordpress from local pc, because too many requests error from server
#    copy:
#      src: wordpress.tar.gz
#      dest: /tmp/wordpress.tar.gz
    
  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www
      remote_src: yes

  - name: Set ownership
    file:
      path: /var/www/wordpress
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: Install wp configuration
    template:
      src: wp-config.php
      dest: /var/www/wordpress/wp-config.php
      
  - name: Add the user for gitlab runner
    become: true
    ansible.builtin.user:
      name: runner

  - name: Add runner user to sudoers
    become: true
    user:
      name=runner
      groups=sudo
      append=yes
      state=present

  - name: Allow gitlab_runner user to have passwordless sudo
    become: true
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^runner'
      line: 'runner ALL=(ALL) NOPASSWD: ALL'

  - name: Create directory for runner authorized_keys
    file:
      name: /home/runner/.ssh/
      state: directory

  - name: Copy authorized_keys file
    become: true
    template:
      src: templates/authorized_keys
      dest: /home/runner/.ssh/
      
  - name: Create directory for project files
    file:
      name: /var/www/wordpress/eksen.space/
      state: directory
      
  - name: Set ownership on project folder
    file:
      path: /var/www/wordpress/eksen.space/
      state: directory
      recurse: yes
      owner: runner
      group: runner
