---
galaxy_info:
  role_name: mysql
  author: geerlingguy, cutted by ek
  description: MySQL server example role for Ubuntu.
  company: "ek"
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all

