---
  - name: Create a new database  
    mysql_db: 
      name: wordpress 
      state: present 
      login_user: wordpress 
      login_password: "wordpress"

  - name: Setup mysql master config
    template:
      src: templates/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: Reload mysql
    service:
      name: mysql
      state: restarted
      enabled: true
