---
  - name: Add hosts in hosts file
    become: true
    lineinfile:
      path: /etc/hosts
      line: 
        - 192.168.1.9  nle.eksen.space
        - 192.168.1.10 db01.eksen.space
        - 192.168.1.11 db02.eksen.space
        - 192.168.1.12 app.eksen.space
        - 192.168.1.13 gitlab.eksen.space
        - 192.168.1.14 runner.eksen.space 
        - 192.168.1.15 monitoring.eksen.space

  - name: Update remote system
    apt:
      update_cache: yes

  - name: Install nginx, squid, letsencrypt
    apt:
      name: 
        - nginx
        - letsencrypt
        - squid
      state: latest

  - name: Create letsencrypt directory
    file:
      name: /var/www/letsencrypt
      state: directory

  - name: Remove default nginx config
    file:
      name: /etc/nginx/sites-enabled/default
      state: absent

  - name: Install nginx http
    template:
      src: templates/nginx-http.j2
      dest: /etc/nginx/sites-enabled/http

  - name: Install nginx config
    become: true
    template:
      src: templates/nginx.conf
      dest: /etc/nginx/nginx.conf
      
  - name: Reload nginx
    service:
      name: nginx
      state: restarted
      enabled: true

  - name: Prepere letsencrypt - create certificate
    shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ email }} --agree-tos -d {{ domain }}
    args:
      creates: /etc/letsencrypt/live/{{ domain }}

#  - name: Copy certs from templates 
#    copy:
#      src: templates/letsencrypt/live/
#      dest: /etc/letsencrypt/live/

  - name: Install nginx config
    become: true
    template:
      src: templates/eksen.space.conf
      dest: /etc/nginx/conf.d/eksen.space.conf

  - name: Configure squid 'allow localnet'
    become: true
    lineinfile:
      path: /etc/squid/squid.conf
      regexp: "^#http_access allow localnet"
      line: http_access allow localnet

  - name: Configure squid ip:port
    become: true
    lineinfile:
      path: /etc/squid/squid.conf
      regexp: http_port 3128
      line: http_port 0.0.0.0:3128

  - name: Reload nginx
    service:
      name: nginx
      state: restarted
      enabled: true
      
  - name: Reload squid
    service:
      name: squid
      state: restarted
      enabled: true
