---
  - name: Updating remote system
    apt:
      update_cache: yes

  - name: Installing nginx and letsencrypt
    apt:
      name: 
        - nginx
        - letsencrypt
      state: latest

  - name: Creating LetsEncrypt directory
    file:
      name: /var/www/letsencrypt
      state: directory

  - name: Removing default site config for nginx
    file:
      name: /etc/nginx/sites-enabled/default
      state: absent

  - name: Installing nginx basic http site for nginx
    template:
      src: templates/nginx-http.j2
      dest: /etc/nginx/sites-enabled/http

  - name: Installing nginx config
    template:
      src: templates/nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: Adding basic html page
    template:
      src: templates/index.html
      dest: /var/www/index.html

  - name: Reloading nginx
    service:
      name: nginx
      state: restarted
      enabled: true

