---
- name: Ensure replication user exists on master.
  mysql_user:
    name: root
    host: db02
    password: root
    state: present
  when:
    - mysql_replication_role == 'master'

- name: Check slave replication status.
  mysql_replication:
    mode: getreplica
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_username }}"
  ignore_errors: true
  register: slave
  when:
    - mysql_replication_role == 'slave'

- name: Check master replication status.
  mysql_replication:
    mode: getprimary
  delegate_to: "{{ mysql_replication_master }}"
  register: master
  when:
    - mysql_replication_role == 'slave'


- name: Configure replication on the slave.
  mysql_replication:
    mode: changeprimary
    master_host: "{{ mysql_replication_master }}"
    master_user: root
    master_password: root
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: true
  when:
    - mysql_replication_role == 'slave'

- name: Start replication.
  mysql_replication:
    mode: startreplica
  when:
    - mysql_replication_role == 'slave'

