---
- name: update
  raw: apt-get update

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

# Install GitLab and its dependencies.
- name: Install GitLab dependencies.
  package:
    name: "{{ gitlab_dependencies }}"
    state: present

- name: Updating remote system
  apt:
    update_cache: yes

- name: Install GitLab dependencies (Debian).
  apt:
    name: gnupg2
    state: present
  when: ansible_os_family == 'Debian'

- name: Gitlab - Get package
  get_url:
    url: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/focal/gitlab-ce_15.2.0-ce.0_amd64.deb/download.deb"
    dest: /tmp/gitlab-ce.deb
    use_proxy: yes
  environment:
    https_proxy: 'http://192.168.1.9:3128'

- name: Gitlab - Install a .deb package
  become: true
  apt:
    deb: /tmp/gitlab-ce.deb
  timeout: 600

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Copy GitLab configuration file.
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
  
- name: Gitlab - Configure to listen on 0.0.0.0:9100
  become: true
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    line: "node_exporter['listen_address'] = '0.0.0.0:9100'"
