global:
  scrape_interval: 15s
  evaluation_interval: 15s 
  
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert.yml

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: 
        - localhost:9090
        - localhost:9100
        - nle.eksen.space:9100
        - db01.eksen.space:9100
        - db02.eksen.space:9100
        - app.eksen.space:9100
        - gitlab.eksen.space:9100
        - runner.eksen.space:9100
